<a href="https://colab.research.google.com/github/ntolayd/CE888/blob/main/Lab4/lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [110]:
import pandas as pd
import numpy as np

In [111]:
data = pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv',header=None)


In [112]:
data = data.replace(99, np.nan)

In [113]:
data.describe()

0             1    ...           99           100
count  24902.000000  16452.000000  ...  10910.000000  9943.000000
mean      72.381174      0.904573  ...     -0.031244     1.354711
std       21.842598      5.171798  ...      5.176806     5.300409
min       36.000000     -9.950000  ...     -9.950000    -9.950000
25%       53.000000     -2.670000  ...     -4.170000    -2.330000
50%       72.000000      1.600000  ...      0.290000     2.140000
75%      100.000000      4.900000  ...      3.980000     5.730000
max      100.000000      9.370000  ...      9.370000     9.370000

[8 rows x 101 columns]

In [114]:
data = data.drop([0], axis=1)

In [132]:
data.shape

(24983, 100)

In [134]:
sorted(data.mean())

[-3.92072789781688,
 -3.104362765315398,
 -2.386882492177367,
 -2.2826727421248414,
 -1.8856804441959503,
 -1.7631531589666969,
 -1.7151830259888905,
 -1.70566664245122,
 -1.627823235442717,
 -1.5569490504010834,
 -1.5435742443674165,
 -1.1149414914189595,
 -1.0817885995174172,
 -1.0215950124530346,
 -0.9336547041528531,
 -0.9260496670656038,
 -0.8798091885400717,
 -0.8620786426186259,
 -0.7627974855477999,
 -0.7576744854326976,
 -0.6347126836911786,
 -0.6240000325716979,
 -0.6234831560885146,
 -0.6051536654184694,
 -0.6025274238051392,
 -0.48585891573930107,
 -0.42882660886627344,
 -0.22954087125595496,
 -0.13860853378044283,
 -0.06946891494305332,
 0.01694054443928221,
 0.09860422768995264,
 0.12270591625476543,
 0.14725799298483627,
 0.15438907653607375,
 0.2793674215259832,
 0.3523769391842546,
 0.3623557576800315,
 0.39779460188976223,
 0.4034934564521284,
 0.4184427934849018,
 0.44874857925073597,
 0.5286579895028575,
 0.6064156451416435,
 0.6236936996484771,
 0.7401507234297903,

In [139]:
data.iloc[16779,79]

-8.54

In [115]:
arr = data.values

In [116]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """

  new_data = orig.copy()
  rated = np.where(~np.isnan(arr))
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [117]:
user_ratings,idx = replace(arr)

In [118]:
user_ratings

array([[-7.82,  8.79, -9.66, ...,   nan,   nan,   nan],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       ...,
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [ 2.43,  2.67, -3.98, ...,   nan,   nan,   nan]])

In [124]:
n_latent_factors = 4

latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [120]:
latent_user_preferences

array([[0.61297817, 0.96602266, 0.56113922, 0.78852887],
       [0.64914282, 0.33161091, 0.26393971, 0.94892024],
       [0.29951754, 0.35036078, 0.87745869, 0.20761362],
       ...,
       [0.21969979, 0.70520465, 0.24856712, 0.83178411],
       [0.9663157 , 0.05728444, 0.81730033, 0.71508874],
       [0.1264497 , 0.2407062 , 0.67834983, 0.95308108]])

In [121]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                if (rating != 99 and not np.isnan(rating)):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        print('Iteration %d/%d:\tMSE=%.6f' % (iteration, iterations, mse))
        mse_history.append(mse)
    return mse_history


In [125]:
sgd(100)

Iteration 0/100:	MSE=25.698012
Iteration 1/100:	MSE=25.016531
Iteration 2/100:	MSE=24.886117
Iteration 3/100:	MSE=24.772425
Iteration 4/100:	MSE=24.658887
Iteration 5/100:	MSE=24.544041
Iteration 6/100:	MSE=24.427570
Iteration 7/100:	MSE=24.309295
Iteration 8/100:	MSE=24.189012
Iteration 9/100:	MSE=24.066412
Iteration 10/100:	MSE=23.941004
Iteration 11/100:	MSE=23.812020
Iteration 12/100:	MSE=23.678288
Iteration 13/100:	MSE=23.538070
Iteration 14/100:	MSE=23.388856
Iteration 15/100:	MSE=23.227127
Iteration 16/100:	MSE=23.048108
Iteration 17/100:	MSE=22.845596
Iteration 18/100:	MSE=22.611991
Iteration 19/100:	MSE=22.338802
Iteration 20/100:	MSE=22.017938
Iteration 21/100:	MSE=21.644058
Iteration 22/100:	MSE=21.217865
Iteration 23/100:	MSE=20.749317
Iteration 24/100:	MSE=20.258790
Iteration 25/100:	MSE=19.774207
Iteration 26/100:	MSE=19.324166
Iteration 27/100:	MSE=18.930168
Iteration 28/100:	MSE=18.602111
Iteration 29/100:	MSE=18.338843
Iteration 30/100:	MSE=18.132136
Iteration 31/100:	

[25.69801200906223,
 25.016531477207646,
 24.886116876428073,
 24.77242509809163,
 24.658886744412854,
 24.54404108071947,
 24.427569886519805,
 24.309295208457716,
 24.189012188026897,
 24.06641177510353,
 23.941003659674127,
 23.81201973509342,
 23.67828814577233,
 23.538070199554937,
 23.388856258369767,
 23.22712688811736,
 23.048108346116074,
 22.84559569729933,
 22.611990815512335,
 22.338802441839523,
 22.017937877717536,
 21.644057982153434,
 21.217864501231436,
 20.749316523083273,
 20.25879016628834,
 19.77420668803801,
 19.3241655064676,
 18.930168055220374,
 18.60211051053299,
 18.338842980363946,
 18.132135971030255,
 17.971099113957568,
 17.845202164075577,
 17.745642939215415,
 17.66561069676459,
 17.60004212409241,
 17.545239654340868,
 17.49851541961994,
 17.457908807377922,
 17.42197753828955,
 17.38964793852701,
 17.36010905625745,
 17.332738106864007,
 17.30704797380117,
 17.282650162212533,
 17.259228581964578,
 17.236520944052103,
 17.21430553748032,
 17.192391835

In [23]:
aidx

(array([13196,   272,  1438, ...,  7591,  2764, 12046]),
 array([83, 36, 65, ..., 64, 76,  5]))

In [127]:
#prediction for validation set
error_list = []
for i,j in zip(idx[0],idx[1]):
  error_list.append(predict_rating(i,j) - arr[i,j])

final_mse = (np.array(error_list)**2).mean()
print(final_mse)

17.294897620781708


In [130]:
#prediction for nans
np.where(np.isnan(arr))

for i,j in zip(np.where(np.isnan(arr))[0], np.where(np.isnan(arr))[1]):
  arr[i,j] = predict_rating(i,j)

In [129]:
np.where(np.isnan(arr))

array([    0,     0,     0, ..., 24982, 24982, 24982])

In [140]:
## movies dataset

movie_items_data = pd.read_excel('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/movies_latent_factors.xlsx', sheet_name='Items')
movie_users_data = pd.read_excel('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/movies_latent_factors.xlsx', sheet_name='Users')

In [162]:
movie_users_data

User   Factor1   Factor2   Factor3  ...  Factor12  Factor13  Factor14  Factor15
0   4768 -0.204024  0.161079 -0.090447  ...  0.355404  0.007108 -0.118663 -0.039125
1    156 -0.189652 -0.178979 -0.091490  ... -0.048606  0.045916  0.113671  0.179873
2   5323 -0.115308 -0.090886 -0.053129  ... -0.019460  0.108372  0.054471 -0.109552
3    174 -0.227462 -0.272532 -0.017231  ... -0.082396  0.036767 -0.165438  0.050692
4   4529 -0.014616 -0.102218 -0.107935  ... -0.132836 -0.039897  0.129063  0.102669
5    783 -0.020301 -0.031919 -0.036955  ...  0.059725 -0.021647  0.039873 -0.061857
6   3878 -0.091462  0.215879 -0.180453  ...  0.214467  0.189250  0.065990  0.102776
7    768  0.000819 -0.009229 -0.019228  ... -0.010051 -0.002108  0.043223 -0.006670
8   4469 -0.030528 -0.011537 -0.042822  ...  0.010926  0.024400  0.005318 -0.007983
9   1882 -0.083093 -0.029160  0.013748  ... -0.113364 -0.021325  0.181508  0.022357
10  4997 -0.185443 -0.276496 -0.781275  ...  0.103116 -0.100563  0.100164  0.043196
11  2067 -0.083242  0.181171 -0.344267  ... -0.127038  0.176661 -0.055812 -0.000042
12  3806 -0.042344 -0.040755 -0.055720  ... -0.040915 -0.130308 -0.021816  0.034549
13  2848 -0.113283 -0.098942 -0.040393  ...  0.036894  0.067105 -0.016780 -0.029503
14  4433 -0.298760 -0.290228 -0.160120  ...  0.071371 -0.415598 -0.022139 -0.183021
15  3519 -0.068454  0.020090  0.039336  ...  0.005171  0.005546  0.020780 -0.023623
16  5338 -0.061259  0.014661  0.011412  ...  0.031774 -0.062413  0.107708  0.065081
17  3947 -0.022340 -0.115285 -0.136980  ... -0.045329 -0.111919  0.066313  0.002395
18  4373 -0.136550 -0.089406 -0.235399  ... -0.028972 -0.175184 -0.058283  0.147797
19  2092 -0.121763  0.011065 -0.037121  ...  0.044754 -0.003087  0.164487 -0.075231
20   525 -0.040290  0.014383 -0.098967  ... -0.025394  0.034079  0.038330 -0.001341
21  4327  0.008227  0.073899 -0.323967  ... -0.106570 -0.051692 -0.093490  0.029534
22  3048 -0.320315  0.078290 -0.083182  ...  0.028016 -0.018100 -0.128452  0.069972
23  2665 -0.076167 -0.006064 -0.001902  ...  0.086562 -0.132328  0.146198  0.029200
24  4940 -0.113099  0.047643 -0.053024  ...  0.010227 -0.008233 -0.029304  0.090511

[25 rows x 16 columns]

In [147]:
movie_items_data.sort_values(by='Factor1', ascending=False)

Movie ID  ...  Factor15
86      4327  ... -2.247246
37       414  ... -1.959942
85      3049  ...  0.128814
90      8467  ...  1.616338
68       854  ... -0.931746
..       ...  ...       ...
16       122  ... -0.314937
59       680  ... -1.833900
27       238  ... -2.267831
33       278  ... -0.779991
50       603  ...  0.752413

[100 rows x 17 columns]

In [161]:
np.array(movie_users_data[movie_users_data['User'] == 2848].loc[:,'Factor1':]).dot(np.array(movie_items_data[movie_items_data['Movie ID']==558].loc[:,'Factor1':]).reshape(-1,1))

array([[0.13261348]])

In [163]:
movie_users_data[movie_users_data['User'] == 3878]

User   Factor1   Factor2   Factor3  ...  Factor12  Factor13  Factor14  Factor15
6  3878 -0.091462  0.215879 -0.180453  ...  0.214467   0.18925   0.06599  0.102776

[1 rows x 16 columns]

In [165]:
np.array(movie_items_data[movie_items_data['Movie ID']==558].loc[:,'Title':])

array([['Spider-Man 2 (2004)', 2.2352233063746585, -0.7881294761636518,
        0.5967221341575716, -0.40008219852561283, -1.246622711078014,
        -1.507203113683306, -0.21991090147438985, -0.4862538356609814,
        0.3316574543781727, -1.8337552665430414, -2.243340340044728,
        -1.1979378607869537, -1.4508122479345416, -2.381119005004064,
        -0.4557528272511082]], dtype=object)

In [169]:
movie_items_data.drop(['Movie ID'],axis=1).values[0][1:]

array([-1.5218476932977845, -1.0385074424076217, 2.0272691992004397,
       0.24793252416549907, -0.5945476708705433, 2.5132599646492184,
       -1.8489100782588614, 0.47670996550851713, -0.22414630395868232,
       -0.7606806322851536, -0.973915043301705, 0.8623788058062587,
       0.4038611510962773, 1.129616009775629, -0.24880587477821164],
      dtype=object)

In [195]:
def recommender(user_id):
  user_array = np.array(movie_users_data[movie_users_data['User'] == user_id].loc[:,'Factor1':])
  df_scores = pd.DataFrame(columns=['ratings','Movie'])
  for i in movie_items_data.drop(['Movie ID'],axis=1).values:
    rating = user_array.dot(i[1:].reshape(-1,1))
    movie_dict = {'ratings':rating, 'Movie':i[0]}
    df_scores = df_scores.append(movie_dict, ignore_index=True)
  return df_scores.sort_values('ratings', ascending=False).head(3)


In [198]:
recommender(2848)

ratings                                              Movie
21   [[1.007056895264574]]                             The Dark Knight (2008)
16  [[0.8444536723338026]]  The Lord of the Rings: The Return of the King ...
14  [[0.7882439990139722]]  The Lord of the Rings: The Fellowship of the R...